# Create traefik Helm release
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
spec:
  chart:
    spec:
      # Use this chart from the repository
      chart: traefik
      # Use this Helm repository
      sourceRef:
        kind: HelmRepository
        name: traefik
      interval: 1m
  postRenderers:
    - kustomize:
        patches:
          # Add labels to all resources
          - target:
              name: .*
            patch: |
              kind: .
              metadata:
                name: .
                labels:
                  layer: infrastructure
  interval: 1m
