# Create mediatunes-traefik Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mediatunes-traefik
spec:
  # Path inside repository to a directory containing Kustomization files
  path: src/clusters/main/databases/mediatunes/kustomize/mediatunes-traefik/kustomize
  dependsOn:
    # Deploy Helm release first
    - name: mediatunes-helm
  # This key always needs to be here for patching to work
  patches: []
