# Create admin ingress route for scorpion
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: scorpion-admin
spec:
  entryPoints:
    # Use entrypoint for HTTPS traffic
    - https
  routes:
    # Match traffic with the Host header
    - match: HostRegexp(`admin\.scorpion\..*`)
      kind: Rule
      services:
        # Route traffic to the scorpion service
        - name: scorpion
          # This is the name of the port in the service
          port: admin
