# Create tailscale Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Include the following configuration files
configurations:
  - configurations/names.yaml
# Include the following resources
resources:
  - resources/helm/release.yaml
  - resources/helm/repository.yaml
  - resources/namespace.yaml
# Set the namespace for all resources
namespace: tailscale
# Set labels for all resources
labels:
  - pairs:
      layer: infrastructure
    includeTemplates: true
# Generate secrets
secretGenerator:
  - files:
      - values.yaml=secrets/values.yaml
    name: tailscale-values
