# Create falcon Helm release
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falcon
spec:
  chart:
    spec:
      # Use this chart from the repository
      chart: falcon
      # Pin version to major
      version: "0.x"
      # Use this Helm repository
      sourceRef:
        kind: HelmRepository
        name: radio-aktywne
  # This key always needs to be here for patching to work
  postRenderers: []
  values:
    falcon:
      urls:
        public: https://falcon.k8s.spietras.dev
        admin: https://admin.falcon.k8s.spietras.dev
      cookies:
        domain: spietras.dev
      orchid:
        public:
          scheme: https
          host: orchid.k8s.spietras.dev
          port: null
      oidc:
        google:
          domain: radioaktywne.pl
      debug: false
  valuesFrom:
    - kind: Secret
      name: falcon-helm-secrets-values
      valuesKey: values.yaml
