# Create podinfo Helm release
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
spec:
  chart:
    spec:
      # Use this chart from the repository
      chart: podinfo
      # Use this Helm repository
      sourceRef:
        kind: HelmRepository
        name: stefanprodan
      interval: 5m
  postRenderers:
    - kustomize:
        patches:
          # Add labels to all resources
          - target:
              name: .*
            patch: |
              kind: .
              metadata:
                name: .
                labels:
                  layer: apps
  interval: 5m
