# Create datashows-traefik Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: datashows-traefik
spec:
  # Path inside repository to a directory containing Kustomization files
  path: src/clusters/main/databases/datashows/kustomize/datashows-traefik/kustomize
  dependsOn:
    # Deploy Helm release first
    - name: datashows-helm
  # This key always needs to be here for patching to work
  patches: []
