# Create emishows-db-traefik Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: emishows-db-traefik
spec:
  # Path inside repository to a directory containing Kustomization files
  path: src/clusters/main/databases/emishows-db/kustomize/emishows-db-traefik/kustomize
  dependsOn:
    # Deploy Helm release first
    - name: emishows-db-helm
  # This key always needs to be here for patching to work
  patches: []
