# Create amber Helm release
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: amber
spec:
  chart:
    spec:
      # Use this chart from the repository
      chart: amber
      # Pin version to major
      version: "0.x"
      # Use this Helm repository
      sourceRef:
        kind: HelmRepository
        name: radio-aktywne
  # This key always needs to be here for patching to work
  postRenderers: []
  values:
    amber:
      urls:
        web: https://web.amber.k8s.spietras.dev
    volume:
      # Use ReadWriteOnce access mode
      access: ReadWriteOnce
      # Use Longhorn storage class
      class: longhorn
      # Use 1 Gigabyte volume size
      size: 1Gi
  valuesFrom:
    - kind: Secret
      name: amber-helm-secrets-values
      valuesKey: values.yaml
