# Create HTTP ingress route for datatimes
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: datatimes-http
spec:
  entryPoints:
    # Use entrypoint for HTTPS traffic
    - https
  routes:
    # Match traffic with the Host header
    - match: HostRegexp(`datatimes\..*`)
      kind: Rule
      services:
        # Route traffic to the datatimes service
        - name: datatimes
          # This is the name of the port in the service
          port: http
