# Create HTTP ingress route for weblounge
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: weblounge-http
spec:
  entryPoints:
    # Use entrypoint for HTTPS traffic
    - https
  routes:
    # Match traffic with the Host header
    - match: HostRegexp(`weblounge\..*`)
      kind: Rule
      services:
        # Route traffic to the weblounge service
        - name: weblounge
          # This is the name of the port in the service
          port: http
