# Create tailscale Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Include the following configuration files
configurations:
  - configurations/names.yaml
# Include the following resources
resources:
  - resources/namespace.yaml
  - resources/release.yaml
  - resources/source.yaml
# Set the namespace for all resources
namespace: tailscale
# Set labels for all resources
labels:
  - pairs:
      layer: infrastructure
    includeTemplates: true
    fields:
      # Set also chart labels in HelmReleases
      - path: spec/chart/metadata/labels
        kind: HelmRelease
        create: true
# Generate secrets
secretGenerator:
  - files:
      - values.yaml=secrets/values.yaml
    name: tailscale-values
