apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
  - kustomizeconfig.yaml
resources:
  - release.yaml
  - source.yaml
secretGenerator:
  - files:
      - values.yaml
    name: tailscale-values
    namespace: default
