apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tailscale
  namespace: default
spec:
  chart:
    spec:
      chart: tailscale-operator
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: default
  interval: 5m
  valuesFrom:
    - kind: Secret
      name: tailscale-values
