# Create mantis-traefik Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mantis-traefik
spec:
  # Path inside repository to a directory containing Kustomization files
  path: src/clusters/main/services/mantis/kustomize/mantis-traefik/kustomize
  dependsOn:
    # Deploy Helm release first
    - name: mantis-helm
  # This key always needs to be here for patching to work
  patches: []
