# Create emischeduler-traefik Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: emischeduler-traefik
spec:
  # Path inside repository to a directory containing Kustomization files
  path: src/clusters/main/apps/emischeduler/kustomize/emischeduler-traefik/kustomize
  dependsOn:
    # Deploy Helm release first
    - name: emischeduler-helm
  # This key always needs to be here for patching to work
  patches: []
