# Create traefik-helm Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-helm
spec:
  # Path inside repository to a directory containing Kustomization files
  path: src/clusters/main/infrastructure/traefik/kustomize/traefik-helm/kustomize
  dependsOn:
    # Deploy namespace first
    - name: traefik-namespace
  # This key always needs to be here for patching to work
  patches: []
