# Create S3 ingress route for minium
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minium-s3
spec:
  entryPoints:
    # Use entrypoint for HTTPS traffic
    - https
  routes:
    # Match traffic with the Host header
    - match: HostRegexp(`minium\..*`)
      kind: Rule
      services:
        # Route traffic to the minium service
        - name: minium
          # This is the name of the port in the service
          port: s3
