# Create RTP ingress route for emipass
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: emipass-rtp
spec:
  entryPoints:
    # Use entrypoint for emipass RTP traffic
    - emipass-rtp
  routes:
    - services:
        # Route traffic to the emipass service
        - name: emipass
          # This is the name of the port in the service
          port: rtp
