# Create SQL ingress route for graphite
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: graphite-sql
spec:
  entryPoints:
    # Use entrypoint for graphite SQL traffic
    - graphite-sql
  routes:
    # Match all traffic
    - match: HostSNI(`*`)
      services:
        # Route traffic to the graphite service
        - name: graphite
          # This is the name of the port in the service
          port: sql
