# Create octopus-helm Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: octopus-helm
spec:
  # Path inside repository to a directory containing Kustomization files
  path: src/clusters/main/services/octopus/kustomize/octopus-helm/kustomize
  dependsOn:
    # Deploy namespace first
    - name: octopus-namespace
  # This key always needs to be here for patching to work
  patches: []
