# Create jasmine-traefik Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jasmine-traefik
spec:
  # Path inside repository to a directory containing Kustomization files
  path: src/clusters/main/apps/jasmine/kustomize/jasmine-traefik/kustomize
  dependsOn:
    # Deploy Helm release first
    - name: jasmine-helm
  # This key always needs to be here for patching to work
  patches: []
