# Create longhorn-helm Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-helm
spec:
  # Path inside repository to a directory containing Kustomization files
  path: src/clusters/main/infrastructure/longhorn/kustomize/longhorn-helm/kustomize
  dependsOn:
    # Deploy namespace first
    - name: longhorn-namespace
  # This key always needs to be here for patching to work
  patches: []
