emerald:
  credentials:
    admin:
      user: ENC[AES256_GCM,data:LJpeuEg=,iv:sTotl2GRyCL3q9ydm8GWWVJRp5M2z3JzorweeaQ0EN8=,tag:WA+ylNWz6eiMPMYrJr4cRg==,type:str]
      password: ENC[AES256_GCM,data:stgVPIDu7jM=,iv:yw/kvoF8nzNY8vm4NeHpquV9jejXj2xn6Rg3aC/J810=,tag:yAGNex8puPtAHY6leJc3iQ==,type:str]
    readonly:
      user: ENC[AES256_GCM,data:cDPiOhpqB8k=,iv:O6dLDXpPh4voysUeOfothaCLe+NVt9sywAONNpvanjo=,tag:G/rvMNkzDJ+nq0SLJwY8cg==,type:str]
      password: ENC[AES256_GCM,data:y6OrcQ/j7Ck=,iv:hIMXeryDepQnV4S8KhbJySSUhbySyOM7peCppJ6vlQM=,tag:4nNeMlNx/w7J3O603QpGvg==,type:str]
    readwrite:
      user: ENC[AES256_GCM,data:QwZjM4A56CMr,iv:vIdePnxZVKF1YwhHjelxcMj6RQ1m527wdOtqQp8mFZM=,tag:636W2Q7fGROgj16Pj+Abwg==,type:str]
      password: ENC[AES256_GCM,data:PLnM2Fusz6g=,iv:BAWcTnfPsLOIMiIiLMZZlP6f+WATip79JqNyQ9Gihmc=,tag:4tIevfvXpFrOUhEZTWGazg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGY1ZoYlZvWG04Zk9ZdXh2
        T0VWUk1oY0R0eEtpQnJRcWIzUXozQUlGOVRNCitxY0h5b3l6QnN2ejNZQ3Z1aXJX
        aWhuNjZtYVNlTi9vV2pJOXJ3dkpZQjQKLS0tIGtJdFNOaDVtWXQ5aTd5L1diTzhw
        c2RmaXczVnY0azVqWEtZTHQ5YUZFYkEK57cPtu0CelzVM9LFR/i3qUbAPt6HRAUZ
        jAlPDHIQqQWeJE7x8E3CwCT3Z7LyA3fgSlt8eZ/n1OE6hNc1uWRz4Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14uepygtepskwehywergh9fe9j2a3ytqd80y9r2ekfmett6rq3peqjtgxns
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOalFvczJlL2xpUlVEblRD
        TGlid0dzRWhxYTBUZENVQzNESGtyTmkvcVFJCmxtWDQyb2VJNUNPaEVJVzVja0RK
        aEVOZ2ZsMmZTckduVGRzcHFWSUFJdjAKLS0tIFRHZ3M0dUlob0p6R0JPQlpSWG0x
        cm1sN3U1VnZNNTU1NFQ2UlRmSUJiVUkKcDxNEToerq/aAa+m8Bmyg9R+UsuMXwx/
        1guqoWy3m4ucGQBi7eCswg5m+rGee+FgzlQsan9EQwL8Zhh8sTwlaQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1y5lqafxarcnlrduh8k3tycnaq63v2alagmtkf0k9gd59pg263axqtt928v
  lastmodified: "2026-10-03T16:47:22Z"
  mac: ENC[AES256_GCM,data:gWojmfrS7muQQFgNcohzEvwN9wjbMk8gt1OtIx0qDWOR7WqJZ1aUk7J8+bjhYYFbSD6FdRCnvF+4eraBYCMsHmgeKTvSFbEACMm1anGoLyGH+6Cqg+c+jFc0L9/iH1/NX3OvEhTEUH/MzOl9ooZpenziWoViGjkQH3PhZG/93IU=,iv:DEjtCL/XG6NxQ8CN6pUnCg7xWhfWiguG3ALzZmIgQDs=,tag:XoH10/9JImAKDXwVjj8tSw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
