# Create web ingress route for emiarchive
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: emiarchive-web
spec:
  entryPoints:
    # Use entrypoint for HTTPS traffic
    - https
  routes:
    # Match traffic with the Host header
    - match: HostRegexp(`web\.emiarchive\..*`)
      kind: Rule
      services:
        # Route traffic to the emiarchive service
        - name: emiarchive
          # This is the name of the port in the service
          port: web
