# Create HTTP ingress route for datashows
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: datashows-http
spec:
  entryPoints:
    # Use entrypoint for HTTPS traffic
    - https
  routes:
    # Match traffic with the Host header
    - match: HostRegexp(`datashows\..*`)
      kind: Rule
      services:
        # Route traffic to the datashows service
        - name: datashows
          # This is the name of the port in the service
          port: http
          # Use HTTPS when communicating with the service
          scheme: https
