# Create SQL ingress route for datashows
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: datashows-sql
spec:
  entryPoints:
    # Use entrypoint for datashows SQL traffic
    - datashows-sql
  routes:
    # Match all traffic
    - match: HostSNI(`*`)
      services:
        # Route traffic to the datashows service
        - name: datashows
          # This is the name of the port in the service
          port: sql
