# Create cert-manager Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
spec:
  # Path inside repository to a directory containing Kustomization files
  path: src/clusters/main/infrastructure/cert-manager/kustomize
  # Set the namespace for all resources
  targetNamespace: cert-manager
  # This needs to be here for patching to work
  patches: []
