diamond:
  credentials:
    user:
      password: ENC[AES256_GCM,data:z20A6JBBZKM=,iv:zwcjutI9h7H9vFcdkF8gC6VqpwKSX7Q3Rnhg7cKIxQ4=,tag:xog2+yWAvmoWrt0LaaENgg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14uepygtepskwehywergh9fe9j2a3ytqd80y9r2ekfmett6rq3peqjtgxns
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGY1ZoYlZvWG04Zk9ZdXh2
        T0VWUk1oY0R0eEtpQnJRcWIzUXozQUlGOVRNCitxY0h5b3l6QnN2ejNZQ3Z1aXJX
        aWhuNjZtYVNlTi9vV2pJOXJ3dkpZQjQKLS0tIGtJdFNOaDVtWXQ5aTd5L1diTzhw
        c2RmaXczVnY0azVqWEtZTHQ5YUZFYkEK57cPtu0CelzVM9LFR/i3qUbAPt6HRAUZ
        jAlPDHIQqQWeJE7x8E3CwCT3Z7LyA3fgSlt8eZ/n1OE6hNc1uWRz4Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1y5lqafxarcnlrduh8k3tycnaq63v2alagmtkf0k9gd59pg263axqtt928v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOalFvczJlL2xpUlVEblRD
        TGlid0dzRWhxYTBUZENVQzNESGtyTmkvcVFJCmxtWDQyb2VJNUNPaEVJVzVja0RK
        aEVOZ2ZsMmZTckduVGRzcHFWSUFJdjAKLS0tIFRHZ3M0dUlob0p6R0JPQlpSWG0x
        cm1sN3U1VnZNNTU1NFQ2UlRmSUJiVUkKcDxNEToerq/aAa+m8Bmyg9R+UsuMXwx/
        1guqoWy3m4ucGQBi7eCswg5m+rGee+FgzlQsan9EQwL8Zhh8sTwlaQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-06T13:21:33Z"
  mac: ENC[AES256_GCM,data:FKVzRERK9VQ8qhjj7RgSfdadTfxi1l+RpYL4lVhRvzLAQ7kisFVoYH21TrxVw9rk8D5GKnv/CTzy5LcKu/DAFG2SehaexI/Ig3Nz8GrYqLXWIzpOwFEZaqgiDd4kK7UM8nzcfaswmv0EtxSeF/7yo0Y+SnvVbd0Zp9WCYGEtMQM=,iv:OpK+81QiEfe3SQ2de75vPWgJbDsxL29OwkBnU3fbvVE=,tag:oCQce1SwB2RCO3SqJOYa4w==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.4
