# Create HTTPS ingress route for emitimes
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: emitimes-https
spec:
  entryPoints:
    # Use entrypoint for secure web traffic
    - websecure
  routes:
    # Match traffic with the Host header
    - match: HostRegexp(`emitimes.{domain:.*}`)
      kind: Rule
      services:
        # Route traffic to the emitimes service
        - name: emitimes
          # This is the name of the port in the service
          port: http
