# Create orchid-traefik Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: orchid-traefik
spec:
  # Path inside repository to a directory containing Kustomization files
  path: src/clusters/main/apps/orchid/kustomize/orchid-traefik/kustomize
  dependsOn:
    # Deploy Helm release first
    - name: orchid-helm
  # This key always needs to be here for patching to work
  patches: []
