# Create pelican-traefik Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pelican-traefik
spec:
  # Path inside repository to a directory containing Kustomization files
  path: src/clusters/main/services/pelican/kustomize/pelican-traefik/kustomize
  dependsOn:
    # Deploy Helm release first
    - name: pelican-helm
    # Deploy Traefik first
    - name: traefik
  # This key always needs to be here for patching to work
  patches: []
