# Create HTTP ingress route for mantis
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mantis-http
spec:
  entryPoints:
    # Use entrypoint for HTTPS traffic
    - https
  routes:
    # Match traffic with the Host header
    - match: HostRegexp(`mantis\..*`)
      kind: Rule
      services:
        # Route traffic to the mantis service
        - name: mantis
          # This is the name of the port in the service
          port: http
