# Create SRT ingress route for emifuse
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: emifuse-srt
spec:
  entryPoints:
    # Use entrypoint for emifuse SRT traffic
    - emifuse-srt
  routes:
    - services:
        # Route traffic to the emifuse service
        - name: emifuse
          # This is the name of the port in the service
          port: srt
