# Create metrics Helm release
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics
spec:
  chart:
    spec:
      # Use this chart from the repository
      chart: metrics-server
      # Pin version to major
      version: "3.x"
      # Use this Helm repository
      sourceRef:
        kind: HelmRepository
        name: metrics
  # This key always needs to be here for patching to work
  postRenderers: []
  values:
    # This key always needs to be here for patching to work
    args: []
    # Use metrics instead of metrics-server for naming
    nameOverride: metrics
