# Create cert-manager Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Include the following configuration files
configurations:
  - configurations/names.yaml
# Include the following resources
resources:
  - resources/helm/release.yaml
  - resources/helm/repository.yaml
  - resources/issuers/letsencrypt.yaml
  - resources/namespace.yaml
# Generate secrets
secretGenerator:
  - files:
      - token=secrets/.cftoken
    name: cloudflare-api-token
