# Create howlite-helm Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: howlite-helm
spec:
  # Path inside repository to a directory containing Kustomization files
  path: src/clusters/main/databases/howlite/kustomize/howlite-helm/kustomize
  dependsOn:
    # Deploy namespace first
    - name: howlite-namespace
  # This key always needs to be here for patching to work
  patches: []
