# Create graphite-helm Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: graphite-helm
spec:
  # Path inside repository to a directory containing Kustomization files
  path: src/clusters/main/databases/graphite/kustomize/graphite-helm/kustomize
  dependsOn:
    # Deploy namespace first
    - name: graphite-namespace
    # Deploy Longhorn first
    - name: longhorn
  # This key always needs to be here for patching to work
  patches: []
