# Create HTTP ingress route for octopus
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: octopus-http
spec:
  entryPoints:
    # Use entrypoint for HTTPS traffic
    - https
  routes:
    # Match traffic with the Host header
    - match: HostRegexp(`octopus\..*`)
      kind: Rule
      services:
        # Route traffic to the octopus service
        - name: octopus
          # This is the name of the port in the service
          port: http
