# Create SRT ingress route for octopus
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: octopus-srt
spec:
  entryPoints:
    # Use entrypoint for octopus SRT traffic
    - octopus-srt
  routes:
    - services:
        # Route traffic to the octopus service
        - name: octopus
          # This is the name of the port in the service
          port: srt
