# Create emipass-traefik Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: emipass-traefik
spec:
  # Path inside repository to a directory containing Kustomization files
  path: src/clusters/main/apps/emipass/kustomize/emipass-traefik/kustomize
  dependsOn:
    # Deploy Helm release first
    - name: emipass-helm
  # This key always needs to be here for patching to work
  patches: []
