# Create tailscale Helm release
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tailscale
spec:
  chart:
    spec:
      # Use this chart from the repository
      chart: tailscale-operator
      # Use this Helm repository
      sourceRef:
        kind: HelmRepository
        name: tailscale
      interval: 1m
  postRenderers:
    - kustomize:
        patches:
          # Add labels to all resources
          - target:
              name: .*
            patch: |
              kind: .
              metadata:
                name: .
                labels:
                  layer: infrastructure
  valuesFrom:
    - kind: Secret
      name: tailscale-values
  interval: 1m
