# Create HTTP ingress route for emicast
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: emicast-http
spec:
  entryPoints:
    # Use entrypoint for HTTPS traffic
    - https
  routes:
    # Match traffic with the Host header
    - match: HostRegexp(`emicast\..*`)
      kind: Rule
      services:
        # Route traffic to the emicast service
        - name: emicast
          # This is the name of the port in the service
          port: http
