# Create HTTP ingress route for howlite
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: howlite-http
spec:
  entryPoints:
    # Use entrypoint for HTTPS traffic
    - https
  routes:
    # Match traffic with the Host header
    - match: HostRegexp(`howlite\..*`)
      kind: Rule
      services:
        # Route traffic to the howlite service
        - name: howlite
          # This is the name of the port in the service
          port: http
