# Create emitimes Helm release
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emitimes
spec:
  chart:
    spec:
      # Use this chart from the repository
      chart: emitimes
      # Use this Helm repository
      sourceRef:
        kind: HelmRepository
        name: radio-aktywne
  # This key always needs to be here for patching to work
  postRenderers: []
  values:
    volume:
      # Use ReadWriteOnce access mode
      access: ReadWriteOnce
      # Use Longhorn storage class
      class: longhorn
