# Create webstream-helm Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: webstream-helm
spec:
  # Path inside repository to a directory containing Kustomization files
  path: src/clusters/main/apps/webstream/kustomize/webstream-helm/kustomize
  dependsOn:
    # Deploy namespace first
    - name: webstream-namespace
  # This key always needs to be here for patching to work
  patches: []
