daisy:
  secrets:
    auth:
      - ENC[AES256_GCM,data:2AoHxWhh,iv:xhAImRxqFvYUDhbB67DK4nfLN9knknHFauZ8tkrYlkY=,tag:YXFhv5jLqcsiRBEHTKJThw==,type:str]
  scorpion:
    public:
      client: ENC[AES256_GCM,data:hr8DIIQ=,iv:+O8po/XTtbh9+KpUI8zzr23Xum7oqGVqOlQoEvW7h70=,tag:D3GkUvFAZUrHEW3mtNJbJQ==,type:str]
      secret: ENC[AES256_GCM,data:KAm6plzQ,iv:5FN002IkylvVROS+xsxSSyuySXsUG1SjqKCXNBkKGfQ=,tag:PgvlrOsscsI+93OQPmc/lg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14uepygtepskwehywergh9fe9j2a3ytqd80y9r2ekfmett6rq3peqjtgxns
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGY1ZoYlZvWG04Zk9ZdXh2
        T0VWUk1oY0R0eEtpQnJRcWIzUXozQUlGOVRNCitxY0h5b3l6QnN2ejNZQ3Z1aXJX
        aWhuNjZtYVNlTi9vV2pJOXJ3dkpZQjQKLS0tIGtJdFNOaDVtWXQ5aTd5L1diTzhw
        c2RmaXczVnY0azVqWEtZTHQ5YUZFYkEK57cPtu0CelzVM9LFR/i3qUbAPt6HRAUZ
        jAlPDHIQqQWeJE7x8E3CwCT3Z7LyA3fgSlt8eZ/n1OE6hNc1uWRz4Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1y5lqafxarcnlrduh8k3tycnaq63v2alagmtkf0k9gd59pg263axqtt928v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOalFvczJlL2xpUlVEblRD
        TGlid0dzRWhxYTBUZENVQzNESGtyTmkvcVFJCmxtWDQyb2VJNUNPaEVJVzVja0RK
        aEVOZ2ZsMmZTckduVGRzcHFWSUFJdjAKLS0tIFRHZ3M0dUlob0p6R0JPQlpSWG0x
        cm1sN3U1VnZNNTU1NFQ2UlRmSUJiVUkKcDxNEToerq/aAa+m8Bmyg9R+UsuMXwx/
        1guqoWy3m4ucGQBi7eCswg5m+rGee+FgzlQsan9EQwL8Zhh8sTwlaQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-04T21:15:38Z"
  mac: ENC[AES256_GCM,data:2JpxdlhQKf6MM383tqY+7zgUyeMFfLGKnXnNcNVNDqHqUAy0UjMoE0lgZ6LKCsdseStDPaZcBIZqAi0/9t71QSO/v6JCXDZas4Hapgl7KQox6vjHqAWC3pGNrsJfWZ4ykuzgE38jor9eJWvRiMc8/8/cMEOuSwbL4VezwL8fhX0=,iv:mnVwrM9ODgnWNbzW4+ekYRlMqaoG5L++mycnAS5RguQ=,tag:porWaO8BELiIjN9Q6GEKsQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
