# Create podinfo Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Include the following resources
resources:
  - resources/namespace.yaml
  - resources/release.yaml
  - resources/source.yaml
# Set the namespace for all resources
namespace: podinfo
# Set labels for all resources
labels:
  - pairs:
      layer: apps
    includeTemplates: true
    fields:
      # Set also chart labels in HelmReleases
      - path: spec/chart/metadata/labels
        kind: HelmRelease
        create: true
