apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  chart:
    spec:
      chart: podinfo
      interval: 1m
      sourceRef:
        kind: HelmRepository
        name: stefanprodan
        namespace: default
  interval: 1m
