# Create webfuse-helm Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: webfuse-helm
spec:
  # Path inside repository to a directory containing Kustomization files
  path: src/clusters/main/apps/webfuse/kustomize/webfuse-helm/kustomize
  dependsOn:
    # Deploy namespace first
    - name: webfuse-namespace
  # This key always needs to be here for patching to work
  patches: []
