# Create HTTP ingress route for emitimes
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: emitimes-http
spec:
  entryPoints:
    # Use entrypoint for HTTPS traffic
    - https
  routes:
    # Match traffic with the Host header
    - match: HostRegexp(`emitimes\..*`)
      kind: Rule
      services:
        # Route traffic to the emitimes service
        - name: emitimes
          # This is the name of the port in the service
          port: http
