tulip:
  secrets:
    auth:
      - ENC[AES256_GCM,data:ML8gFemA,iv:kS3ZrG7xbbM9rw2ZFLw/zbLV0lyITVSZa1Up8+I2LH8=,tag:sOAwI44f5a3hyXs3m2iQpg==,type:str]
  scorpion:
    public:
      client: ENC[AES256_GCM,data:7ng4q4o=,iv:Eu/6L4/FZ9NeRNdRlzlgDHxD3d7YYxo5tobQkNQZBRQ=,tag:CP1c8wltjWJxtrv78H2MzQ==,type:str]
      secret: ENC[AES256_GCM,data:jLrde3Sr,iv:9O4t/ScdM71U23CemH5oqesvYmDjb6wH2HxCrN4fx4o=,tag:taEhU9JmqGrz3Bmt7G3h3Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14uepygtepskwehywergh9fe9j2a3ytqd80y9r2ekfmett6rq3peqjtgxns
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGY1ZoYlZvWG04Zk9ZdXh2
        T0VWUk1oY0R0eEtpQnJRcWIzUXozQUlGOVRNCitxY0h5b3l6QnN2ejNZQ3Z1aXJX
        aWhuNjZtYVNlTi9vV2pJOXJ3dkpZQjQKLS0tIGtJdFNOaDVtWXQ5aTd5L1diTzhw
        c2RmaXczVnY0azVqWEtZTHQ5YUZFYkEK57cPtu0CelzVM9LFR/i3qUbAPt6HRAUZ
        jAlPDHIQqQWeJE7x8E3CwCT3Z7LyA3fgSlt8eZ/n1OE6hNc1uWRz4Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1y5lqafxarcnlrduh8k3tycnaq63v2alagmtkf0k9gd59pg263axqtt928v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOalFvczJlL2xpUlVEblRD
        TGlid0dzRWhxYTBUZENVQzNESGtyTmkvcVFJCmxtWDQyb2VJNUNPaEVJVzVja0RK
        aEVOZ2ZsMmZTckduVGRzcHFWSUFJdjAKLS0tIFRHZ3M0dUlob0p6R0JPQlpSWG0x
        cm1sN3U1VnZNNTU1NFQ2UlRmSUJiVUkKcDxNEToerq/aAa+m8Bmyg9R+UsuMXwx/
        1guqoWy3m4ucGQBi7eCswg5m+rGee+FgzlQsan9EQwL8Zhh8sTwlaQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-05T23:18:01Z"
  mac: ENC[AES256_GCM,data:k+T5gtL2UEKNZiYjzZ6T0zvGEHTo0qSDhIyHgz9erMXFnLMBxAu79GGnLsIaLw/F6Y5LRd7bHB6rBzazEVy+s1B5p0qj/Q5EuJ4mE6cj11ODu2qgcK6cYivKc2mMOjs1ttynSyGdTuhO3dif3VScMG9S2e4PJygr+nVFdd8ew5k=,iv:ZgfPryZ/RA32KlyuJudcQdMyj3snI4ZV8h9ZfG8U5Y8=,tag:LY6Xu2zKR91utFHRYhov4g==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
