# Create S3 ingress route for mediarecords
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mediarecords-s3
spec:
  entryPoints:
    # Use entrypoint for HTTPS traffic
    - https
  routes:
    # Match traffic with the Host header
    - match: HostRegexp(`mediarecords\..*`)
      kind: Rule
      services:
        # Route traffic to the mediarecords service
        - name: mediarecords
          # This is the name of the port in the service
          port: s3
