# Configure vars transformer
varReference:
  - group: traefik.io
    kind: Middleware
    path: spec/plugin/traefikoidc/clientSecret
  - group: traefik.io
    kind: Middleware
    path: spec/plugin/traefikoidc/redis/password
  - group: traefik.io
    kind: Middleware
    path: spec/plugin/traefikoidc/sessionEncryptionKey
