# Create HTTP ingress route for datatunes
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: datatunes-http
spec:
  entryPoints:
    # Use entrypoint for HTTPS traffic
    - https
  routes:
    # Match traffic with the Host header
    - match: HostRegexp(`datatunes\..*`)
      kind: Rule
      services:
        # Route traffic to the datatunes service
        - name: datatunes
          # This is the name of the port in the service
          port: http
          # Use HTTPS when communicating with the service
          scheme: https
