# Create SQL ingress route for datatunes
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: datatunes-sql
spec:
  entryPoints:
    # Use entrypoint for datatunes SQL traffic
    - datatunes-sql
  routes:
    # Match all traffic
    - match: HostSNI(`*`)
      services:
        # Route traffic to the datatunes service
        - name: datatunes
          # This is the name of the port in the service
          port: sql
