# Create quokka-helm Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: quokka-helm
spec:
  # Path inside repository to a directory containing Kustomization files
  path: src/clusters/main/services/quokka/kustomize/quokka-helm/kustomize
  dependsOn:
    # Deploy namespace first
    - name: quokka-namespace
  # This key always needs to be here for patching to work
  patches: []
