# Create HTTP ingress route for emirecorder
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: emirecorder-http
spec:
  entryPoints:
    # Use entrypoint for HTTPS traffic
    - https
  routes:
    # Match traffic with the Host header
    - match: HostRegexp(`emirecorder\..*`)
      kind: Rule
      services:
        # Route traffic to the emirecorder service
        - name: emirecorder
          # This is the name of the port in the service
          port: http
