# Create SRT ingress route for emirecorder
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: emirecorder-srt
spec:
  entryPoints:
    # Use entrypoint for emirecorder SRT traffic
    - emirecorder-srt
  routes:
    - services:
        # Route traffic to the emirecorder service
        - name: emirecorder
          # This is the name of the port in the service
          port: srt
