# Create HTTP ingress route for webrecords
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: webrecords-http
spec:
  entryPoints:
    # Use entrypoint for HTTPS traffic
    - https
  routes:
    # Match traffic with the Host header
    - match: HostRegexp(`webrecords\..*`)
      kind: Rule
      services:
        # Route traffic to the webrecords service
        - name: webrecords
          # This is the name of the port in the service
          port: http
