# Create HTTP ingress route for sapphire
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sapphire-http
spec:
  entryPoints:
    # Use entrypoint for HTTPS traffic
    - https
  routes:
    # Match traffic with the Host header
    - match: HostRegexp(`sapphire\..*`)
      kind: Rule
      services:
        # Route traffic to the sapphire service
        - name: sapphire
          # This is the name of the port in the service
          port: http
          # Use HTTPS when communicating with the service
          scheme: https
