# Create SQL ingress route for sapphire
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: sapphire-sql
spec:
  entryPoints:
    # Use entrypoint for sapphire SQL traffic
    - sapphire-sql
  routes:
    # Match all traffic
    - match: HostSNI(`*`)
      services:
        # Route traffic to the sapphire service
        - name: sapphire
          # This is the name of the port in the service
          port: sql
