# Create HTTP ingress route for webfuse
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: webfuse-http
spec:
  entryPoints:
    # Use entrypoint for HTTPS traffic
    - https
  routes:
    # Match traffic with the Host header
    - match: HostRegexp(`webfuse\..*`)
      kind: Rule
      services:
        # Route traffic to the webfuse service
        - name: webfuse
          # This is the name of the port in the service
          port: http
