# Create traefik Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Include the following resources
resources:
  - resources/namespace.yaml
  - resources/release.yaml
  - resources/source.yaml
# Set the namespace for all resources
namespace: traefik
# Set labels for all resources
labels:
  - pairs:
      layer: infrastructure
    includeTemplates: true
