# Create emirecorder-helm Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: emirecorder-helm
spec:
  # Path inside repository to a directory containing Kustomization files
  path: src/clusters/main/apps/emirecorder/kustomize/emirecorder-helm/kustomize
  dependsOn:
    # Deploy namespace first
    - name: emirecorder-namespace
  # This key always needs to be here for patching to work
  patches: []
