# Create tailscale Helm repository
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: tailscale
spec:
  type: default
  url: https://pkgs.tailscale.com/helmcharts
  interval: 5m
