# Create HTTP ingress route for emilounge
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: emilounge-http
spec:
  entryPoints:
    # Use entrypoint for HTTPS traffic
    - https
  routes:
    # Match traffic with the Host header
    - match: HostRegexp(`emilounge\..*`)
      kind: Rule
      services:
        # Route traffic to the emilounge service
        - name: emilounge
          # This is the name of the port in the service
          port: http
