# Create cert-manager-issuers Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Include the following configuration files
configurations:
  - configurations/names.yaml
# Include the following resources
resources:
  - resources/letsencrypt.yaml
# Generate secrets
secretGenerator:
  - files:
      - .cftoken=secrets/.cftoken
    name: cert-manager-issuers-secrets-cftoken
