# Create webscheduler-helm Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: webscheduler-helm
spec:
  # Path inside repository to a directory containing Kustomization files
  path: src/clusters/main/apps/webscheduler/kustomize/webscheduler-helm/kustomize
  dependsOn:
    # Deploy namespace first
    - name: webscheduler-namespace
  # This key always needs to be here for patching to work
  patches: []
