# Create HTTP ingress route for webstream
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: webstream-http
spec:
  entryPoints:
    # Use entrypoint for HTTPS traffic
    - https
  routes:
    # Match traffic with the Host header
    - match: HostRegexp(`webstream\..*`)
      kind: Rule
      services:
        # Route traffic to the webstream service
        - name: webstream
          # This is the name of the port in the service
          port: http
