# Create tailscale Helm release
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tailscale
spec:
  chart:
    spec:
      # Use this chart from the repository
      chart: tailscale-operator
      # Use this Helm repository
      sourceRef:
        kind: HelmRepository
        name: tailscale
  # This key always needs to be here for patching to work
  postRenderers: []
  valuesFrom:
    - kind: Secret
      name: tailscale-helm-secrets-values
      valuesKey: values.yaml
