scorpion:
  secrets:
    system:
      - ENC[AES256_GCM,data:7LSGi+dLFXdrtTALIW8w/iZI,iv:FkJJJyM08dLH7GR+VkhuJdsSW6o4vu0bXRKYPEbPqyc=,tag:vCwpw5BEiL0ImQyXLiZU4g==,type:str]
    cookie:
      - ENC[AES256_GCM,data:PsLehl5I7tLEbph/lALGCTUc,iv:RY6AgCyVU/kaoIxENZkqJB8SY4QyuXJgmlX3j67IuUA=,tag:Sbw6gAUJNAbefV7anc5ldw==,type:str]
  diamond:
    sql:
      password: ENC[AES256_GCM,data:HhcYGvMvifU=,iv:sRCm5V6CG9LSWJiE19bSiIb5RSibKNOUu9La4JoNXYs=,tag:5d8gzothUdim5Rm/ExOhJw==,type:str]
sops:
  age:
    - recipient: age14uepygtepskwehywergh9fe9j2a3ytqd80y9r2ekfmett6rq3peqjtgxns
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGY1ZoYlZvWG04Zk9ZdXh2
        T0VWUk1oY0R0eEtpQnJRcWIzUXozQUlGOVRNCitxY0h5b3l6QnN2ejNZQ3Z1aXJX
        aWhuNjZtYVNlTi9vV2pJOXJ3dkpZQjQKLS0tIGtJdFNOaDVtWXQ5aTd5L1diTzhw
        c2RmaXczVnY0azVqWEtZTHQ5YUZFYkEK57cPtu0CelzVM9LFR/i3qUbAPt6HRAUZ
        jAlPDHIQqQWeJE7x8E3CwCT3Z7LyA3fgSlt8eZ/n1OE6hNc1uWRz4Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1y5lqafxarcnlrduh8k3tycnaq63v2alagmtkf0k9gd59pg263axqtt928v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOalFvczJlL2xpUlVEblRD
        TGlid0dzRWhxYTBUZENVQzNESGtyTmkvcVFJCmxtWDQyb2VJNUNPaEVJVzVja0RK
        aEVOZ2ZsMmZTckduVGRzcHFWSUFJdjAKLS0tIFRHZ3M0dUlob0p6R0JPQlpSWG0x
        cm1sN3U1VnZNNTU1NFQ2UlRmSUJiVUkKcDxNEToerq/aAa+m8Bmyg9R+UsuMXwx/
        1guqoWy3m4ucGQBi7eCswg5m+rGee+FgzlQsan9EQwL8Zhh8sTwlaQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-11T15:47:36Z"
  mac: ENC[AES256_GCM,data:e0Kf/vM4RMledJcGuvb16jiieG3oQxanCPfYjuikzkvoY5BlW3pl2IpWRrc5PI70S/IrBHXvAoL030lumbot4sWx9kb+NnZKCiFt5+80sng0pkaMtT/xlUiC3Li5r2+CtG2iNA813/UDljlkjNPfUVgEVpzc8Kn9za58hAxyzzc=,iv:ZkEnC827++d5rRUVH+U8aKYiadEtChfTv4c3Spvp2Dg=,tag:SCop9A9fLIBMYQ7aziU9DQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
