scorpion:
  clients:
    traefik:
      client_secret: ENC[AES256_GCM,data:azNfchuf,iv:cGdzLxrMr6DYKr3S48IZlj/NhnTfW2K/UP0xLKoqSoE=,tag:UhgKuVPXni1kTv6/e3v/yA==,type:str]
  diamond:
    sql:
      password: ENC[AES256_GCM,data:HhcYGvMvifU=,iv:sRCm5V6CG9LSWJiE19bSiIb5RSibKNOUu9La4JoNXYs=,tag:5d8gzothUdim5Rm/ExOhJw==,type:str]
  secrets:
    cookie:
      - ENC[AES256_GCM,data:PsLehl5I7tLEbph/lALGCTUc,iv:RY6AgCyVU/kaoIxENZkqJB8SY4QyuXJgmlX3j67IuUA=,tag:Sbw6gAUJNAbefV7anc5ldw==,type:str]
    system:
      - ENC[AES256_GCM,data:7LSGi+dLFXdrtTALIW8w/iZI,iv:FkJJJyM08dLH7GR+VkhuJdsSW6o4vu0bXRKYPEbPqyc=,tag:vCwpw5BEiL0ImQyXLiZU4g==,type:str]
sops:
  age:
    - recipient: age14uepygtepskwehywergh9fe9j2a3ytqd80y9r2ekfmett6rq3peqjtgxns
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGY1ZoYlZvWG04Zk9ZdXh2
        T0VWUk1oY0R0eEtpQnJRcWIzUXozQUlGOVRNCitxY0h5b3l6QnN2ejNZQ3Z1aXJX
        aWhuNjZtYVNlTi9vV2pJOXJ3dkpZQjQKLS0tIGtJdFNOaDVtWXQ5aTd5L1diTzhw
        c2RmaXczVnY0azVqWEtZTHQ5YUZFYkEK57cPtu0CelzVM9LFR/i3qUbAPt6HRAUZ
        jAlPDHIQqQWeJE7x8E3CwCT3Z7LyA3fgSlt8eZ/n1OE6hNc1uWRz4Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1y5lqafxarcnlrduh8k3tycnaq63v2alagmtkf0k9gd59pg263axqtt928v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOalFvczJlL2xpUlVEblRD
        TGlid0dzRWhxYTBUZENVQzNESGtyTmkvcVFJCmxtWDQyb2VJNUNPaEVJVzVja0RK
        aEVOZ2ZsMmZTckduVGRzcHFWSUFJdjAKLS0tIFRHZ3M0dUlob0p6R0JPQlpSWG0x
        cm1sN3U1VnZNNTU1NFQ2UlRmSUJiVUkKcDxNEToerq/aAa+m8Bmyg9R+UsuMXwx/
        1guqoWy3m4ucGQBi7eCswg5m+rGee+FgzlQsan9EQwL8Zhh8sTwlaQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-17T23:58:39Z"
  mac: ENC[AES256_GCM,data:DDEkFX8St7gyLYuFxpGpvRHDc/xFfeHQ5uuQiyI0lnWaR27ZT5AdNLTnNzT4ZxWjOivv3FiAB8vSCoZKTSYK5HGev8QsFIwiDp+9p5tQnd9nAcSqCPhBtHtOb9ra/bX0qTqCAD0svS6DgO9r1vWkDZG+ZB3wvNUYgj+JHo1flhk=,iv:j9wwzAmyuu1Em1jfuqvGXaSyPXobjUdUAeGzvWP7kOU=,tag:NDbyd4pODg8X08cPrikfNQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
