scorpion:
  secrets:
    system:
      - ENC[AES256_GCM,data:7LSGi+dLFXdrtTALIW8w/iZI,iv:FkJJJyM08dLH7GR+VkhuJdsSW6o4vu0bXRKYPEbPqyc=,tag:vCwpw5BEiL0ImQyXLiZU4g==,type:str]
    cookie:
      - ENC[AES256_GCM,data:PsLehl5I7tLEbph/lALGCTUc,iv:RY6AgCyVU/kaoIxENZkqJB8SY4QyuXJgmlX3j67IuUA=,tag:Sbw6gAUJNAbefV7anc5ldw==,type:str]
  diamond:
    sql:
      password: ENC[AES256_GCM,data:HhcYGvMvifU=,iv:sRCm5V6CG9LSWJiE19bSiIb5RSibKNOUu9La4JoNXYs=,tag:5d8gzothUdim5Rm/ExOhJw==,type:str]
  clients:
    aster:
      secret: ENC[AES256_GCM,data:Q/UqmYAu,iv:Mpu8/iWOOTvgvsWpa/AwTDGAqvVHMx+p8zJlbDwDXZE=,tag:oBwmyAtYcnzuA6fXESS8qg==,type:str]
    daisy:
      secret: ENC[AES256_GCM,data:8qp4geoH,iv:wMm3OZ8RJ7VXCEKSd6v0ZM3rv0c+ldUyIO+kjZH7h+k=,tag:Yh0+7OtOKcSE5gdOvbDV+A==,type:str]
    jasmine:
      secret: ENC[AES256_GCM,data:j75lL9qy,iv:zRER+jfKZ5VnPluqWDWTyggn4ZHn09GYD6oxEhInwcg=,tag:8I5ClJNvoJccSDrIzKjf1Q==,type:str]
    lotus:
      secret: ENC[AES256_GCM,data:bw2S/prd,iv:33sfeW4o5kbysaHHWWSOmEqigenerWwajb2b7lopy7I=,tag:3nQmIIJihJOCG9KWcLKM3A==,type:str]
    magnolia:
      secret: ENC[AES256_GCM,data:QY5xOnjT,iv:8NrsFfHagO3qfcb3w5wSDn2kskwYcsHj5BB1wr8+Bbg=,tag:dB0iKKDgDjRmvyBFanCz3w==,type:str]
    poppy:
      secret: ENC[AES256_GCM,data:eYMKSyLu,iv:nMYakPeh7VdqexBcho90YavgkD5r7prrTIm57o49YdE=,tag:5JCpm4FgPWTHGbek0XDvpw==,type:str]
    tulip:
      secret: ENC[AES256_GCM,data:Oe026JKw,iv:w+3wN9PpBCDQm2Iv3veZI2B/vA4wvy+Yh4sYe4s30Ew=,tag:6U8CG1ASYdXaCtwOpUtxzw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14uepygtepskwehywergh9fe9j2a3ytqd80y9r2ekfmett6rq3peqjtgxns
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGY1ZoYlZvWG04Zk9ZdXh2
        T0VWUk1oY0R0eEtpQnJRcWIzUXozQUlGOVRNCitxY0h5b3l6QnN2ejNZQ3Z1aXJX
        aWhuNjZtYVNlTi9vV2pJOXJ3dkpZQjQKLS0tIGtJdFNOaDVtWXQ5aTd5L1diTzhw
        c2RmaXczVnY0azVqWEtZTHQ5YUZFYkEK57cPtu0CelzVM9LFR/i3qUbAPt6HRAUZ
        jAlPDHIQqQWeJE7x8E3CwCT3Z7LyA3fgSlt8eZ/n1OE6hNc1uWRz4Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1y5lqafxarcnlrduh8k3tycnaq63v2alagmtkf0k9gd59pg263axqtt928v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOalFvczJlL2xpUlVEblRD
        TGlid0dzRWhxYTBUZENVQzNESGtyTmkvcVFJCmxtWDQyb2VJNUNPaEVJVzVja0RK
        aEVOZ2ZsMmZTckduVGRzcHFWSUFJdjAKLS0tIFRHZ3M0dUlob0p6R0JPQlpSWG0x
        cm1sN3U1VnZNNTU1NFQ2UlRmSUJiVUkKcDxNEToerq/aAa+m8Bmyg9R+UsuMXwx/
        1guqoWy3m4ucGQBi7eCswg5m+rGee+FgzlQsan9EQwL8Zhh8sTwlaQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-09T21:52:47Z"
  mac: ENC[AES256_GCM,data:HdCNKK98FJ2K3IPWiaXDbhUybAogKXqqTdrA3OZRsPYQfTjsHygDns3LNIGdUD4jRKeWcz0dr/PnGCIMM9IljNhAxTFVBmAevnFXqLaPKUQfMQNPfNMUjEJwuODcC5hYQ3bUtFOmZrsYMVcNN05C6qmj7r23MrcH2/1Tk6TGXiY=,iv:c3jjuO0kDlcUS8KKfU8vB5vz79q6D0KBPARB6xn7IuM=,tag:MtIcQuUOzrKzf/3ekNOb4w==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
