# Create emistream-namespace Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: emistream-namespace
spec:
  # Path inside repository to a directory containing Kustomization files
  path: src/clusters/main/apps/emistream/kustomize/emistream-namespace/kustomize
  # This key always needs to be here for patching to work
  patches: []
