poppy:
  secrets:
    auth:
      - ENC[AES256_GCM,data:IYkY+sNq,iv:X8L33p9Z1Vaxm6+HzeQgeBguD7Umjf/u4FZ3hctuUps=,tag:BvtGNNF6wbFZ4NZh5xw2qA==,type:str]
  scorpion:
    public:
      client: ENC[AES256_GCM,data:r0CGG2Y=,iv:BbCQo5gD3r3SVkk05YvfOhyECFNDTd4S5/Frx9AO6OI=,tag:I3x2NzHY7TeO8xqb75gzjw==,type:str]
      secret: ENC[AES256_GCM,data:lF8B8Wkx,iv:I/7d5rENAwJpNpO3AlvhFMbLG7EqQzdIsyiFHxJBPMY=,tag:KDTYNkWV3Z3PcWmG3CMnTA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14uepygtepskwehywergh9fe9j2a3ytqd80y9r2ekfmett6rq3peqjtgxns
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGY1ZoYlZvWG04Zk9ZdXh2
        T0VWUk1oY0R0eEtpQnJRcWIzUXozQUlGOVRNCitxY0h5b3l6QnN2ejNZQ3Z1aXJX
        aWhuNjZtYVNlTi9vV2pJOXJ3dkpZQjQKLS0tIGtJdFNOaDVtWXQ5aTd5L1diTzhw
        c2RmaXczVnY0azVqWEtZTHQ5YUZFYkEK57cPtu0CelzVM9LFR/i3qUbAPt6HRAUZ
        jAlPDHIQqQWeJE7x8E3CwCT3Z7LyA3fgSlt8eZ/n1OE6hNc1uWRz4Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1y5lqafxarcnlrduh8k3tycnaq63v2alagmtkf0k9gd59pg263axqtt928v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOalFvczJlL2xpUlVEblRD
        TGlid0dzRWhxYTBUZENVQzNESGtyTmkvcVFJCmxtWDQyb2VJNUNPaEVJVzVja0RK
        aEVOZ2ZsMmZTckduVGRzcHFWSUFJdjAKLS0tIFRHZ3M0dUlob0p6R0JPQlpSWG0x
        cm1sN3U1VnZNNTU1NFQ2UlRmSUJiVUkKcDxNEToerq/aAa+m8Bmyg9R+UsuMXwx/
        1guqoWy3m4ucGQBi7eCswg5m+rGee+FgzlQsan9EQwL8Zhh8sTwlaQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-06T13:44:37Z"
  mac: ENC[AES256_GCM,data:iyvMMmSLiVgYIe7U/kf6NIRN80gv63kxHyf5305lRnuYx9AlWayy0CfnG2sfWfNic7MWrJDKn1XsuNT0wTWq8QJbs+Jb1lK3n/Fmsej+zQ32PR8xxkTbJwkjrUkLMrhIyJTJb1ykTDxWUW6vWTPDc+Fybf8eHN/tNXUa8HSOvfc=,iv:dMeulLfmlS9PxNM4zI//VUJPgzWBY6aZ8Xcwv6e2C5s=,tag:3ty0dN1K4BtzlnoDeYkIpQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
