database:
  credentials:
    user: ENC[AES256_GCM,data:e3Lxmw==,iv:kkYbb2YlTDc9ubup5qMIox0eyVi5Xwzo1n4DPazAA88=,tag:luFqkBruid8NT47+8Ms5gg==,type:str]
    password: ENC[AES256_GCM,data:mABFXc8ketA=,iv:GkDsKthZn4lJzGgPMCGJPNqaBoxlzjgM/J1mr86VUQY=,tag:WNAavnRAqYmHMZNqoP13eg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14uepygtepskwehywergh9fe9j2a3ytqd80y9r2ekfmett6rq3peqjtgxns
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGY1ZoYlZvWG04Zk9ZdXh2
        T0VWUk1oY0R0eEtpQnJRcWIzUXozQUlGOVRNCitxY0h5b3l6QnN2ejNZQ3Z1aXJX
        aWhuNjZtYVNlTi9vV2pJOXJ3dkpZQjQKLS0tIGtJdFNOaDVtWXQ5aTd5L1diTzhw
        c2RmaXczVnY0azVqWEtZTHQ5YUZFYkEK57cPtu0CelzVM9LFR/i3qUbAPt6HRAUZ
        jAlPDHIQqQWeJE7x8E3CwCT3Z7LyA3fgSlt8eZ/n1OE6hNc1uWRz4Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1y5lqafxarcnlrduh8k3tycnaq63v2alagmtkf0k9gd59pg263axqtt928v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOalFvczJlL2xpUlVEblRD
        TGlid0dzRWhxYTBUZENVQzNESGtyTmkvcVFJCmxtWDQyb2VJNUNPaEVJVzVja0RK
        aEVOZ2ZsMmZTckduVGRzcHFWSUFJdjAKLS0tIFRHZ3M0dUlob0p6R0JPQlpSWG0x
        cm1sN3U1VnZNNTU1NFQ2UlRmSUJiVUkKcDxNEToerq/aAa+m8Bmyg9R+UsuMXwx/
        1guqoWy3m4ucGQBi7eCswg5m+rGee+FgzlQsan9EQwL8Zhh8sTwlaQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-04-29T19:30:41Z"
  mac: ENC[AES256_GCM,data:I2NRgsArrMk0axOgcGRJhCzmQj3PmflHIwtNZPraecix1wMO+bzv+t4IU2YWCPRT9eQtk14yuSPHEmEVXDStl2Gh5i6ZnWvDtT0ubh3kB59IyGA8zcq0012xZQNV8Ni8OZnrwflZnBgQd2QCivml+EDwvWZe8YMLlwVmiCQIDxU=,iv:CNPBJaGc+jtxmnZhYmYGkP7RzTqQdESouX2SFA49OSM=,tag:lrYCm9H22BxVIA7BdvlO2w==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
