# Create HTTP ingress route for numbat
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: numbat-http
spec:
  entryPoints:
    # Use entrypoint for HTTPS traffic
    - https
  routes:
    # Match traffic with the Host header
    - match: HostRegexp(`numbat\..*`)
      kind: Rule
      services:
        # Route traffic to the numbat service
        - name: numbat
          # This is the name of the port in the service
          port: http
