# Create crocus Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Include the following resources
resources:
  - crocus-helm/crocus-helm.yaml
  - crocus-namespace/crocus-namespace.yaml
  - crocus-traefik/crocus-traefik.yaml
