numbat:
  amber:
    s3:
      user: ENC[AES256_GCM,data:sdyDjY1WAbSf,iv:gqTwWWOfXxx6SVqMKXJh7mE3VCZjUhYRNjDIw6WJhqw=,tag:VuYHLrZvU+Gpsa00lHURUA==,type:str]
      password: ENC[AES256_GCM,data:lVzSH8fqF9w=,iv:4B51fO26wShAb3zb+wxCBZqHmc7krVMQb7kPCkGfcI4=,tag:s6FzA+uBGsHOUYIzXbmHnw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14uepygtepskwehywergh9fe9j2a3ytqd80y9r2ekfmett6rq3peqjtgxns
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGY1ZoYlZvWG04Zk9ZdXh2
        T0VWUk1oY0R0eEtpQnJRcWIzUXozQUlGOVRNCitxY0h5b3l6QnN2ejNZQ3Z1aXJX
        aWhuNjZtYVNlTi9vV2pJOXJ3dkpZQjQKLS0tIGtJdFNOaDVtWXQ5aTd5L1diTzhw
        c2RmaXczVnY0azVqWEtZTHQ5YUZFYkEK57cPtu0CelzVM9LFR/i3qUbAPt6HRAUZ
        jAlPDHIQqQWeJE7x8E3CwCT3Z7LyA3fgSlt8eZ/n1OE6hNc1uWRz4Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1y5lqafxarcnlrduh8k3tycnaq63v2alagmtkf0k9gd59pg263axqtt928v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOalFvczJlL2xpUlVEblRD
        TGlid0dzRWhxYTBUZENVQzNESGtyTmkvcVFJCmxtWDQyb2VJNUNPaEVJVzVja0RK
        aEVOZ2ZsMmZTckduVGRzcHFWSUFJdjAKLS0tIFRHZ3M0dUlob0p6R0JPQlpSWG0x
        cm1sN3U1VnZNNTU1NFQ2UlRmSUJiVUkKcDxNEToerq/aAa+m8Bmyg9R+UsuMXwx/
        1guqoWy3m4ucGQBi7eCswg5m+rGee+FgzlQsan9EQwL8Zhh8sTwlaQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-10-21T18:46:28Z"
  mac: ENC[AES256_GCM,data:/u5Nym9yn17X9aqdcKdoLT6douQ6EEmknQ4rJZKxIyP0sCmWPNwwvPlMljB3LsUtxh8DCSC8l817hTSyeoXnYqb5UMR/Rb4QyndqtI86UWU2usxeZocMHtuL/BbYHj6uQ85JfqTmaqJgvA7wtFnjVxxyfCQzaRkOCGgOSVYKdFI=,iv:kQ52U2yGRRzrgBnWXLuzczqcht6PJEbJg4jKVf2QNqk=,tag:Tw30K21poQVTfKpsLizZqQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
