# Create HTTP ingress route for webshows
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: webshows-http
spec:
  entryPoints:
    # Use entrypoint for HTTPS traffic
    - https
  routes:
    # Match traffic with the Host header
    - match: HostRegexp(`webshows\..*`)
      kind: Rule
      services:
        # Route traffic to the webshows service
        - name: webshows
          # This is the name of the port in the service
          port: http
