quokka:
  credentials:
    source:
      user: ENC[AES256_GCM,data:7wIEbNEU,iv:VsGCyaBD+w/KIRRmLMkMFEXzkSuHNkLpmbP3fLKY99c=,tag:M9mxrevEBm46SP9l2Et5Jw==,type:str]
      password: ENC[AES256_GCM,data:IU9qKdEUvyI=,iv:RSv5BVc7Z8Kh+01GS21bLIMIq+L3GLd5en3Nr7Yjjg0=,tag:I8bpEbFoWpZudJfQ0E5zjQ==,type:str]
    admin:
      user: ENC[AES256_GCM,data:SZMoxO0=,iv:HCiIixY/s2ZRQWtIdj7azcV/9+bGA5zoPJ6fg2GOwe8=,tag:t/mFtshte6A4B5zZ0OQsyw==,type:str]
      password: ENC[AES256_GCM,data:CvNusGnAaCc=,iv:pVw/+V8oSqwLqOTYPenhqOI54eYtV7I1kIq6lcPE640=,tag:K2PKQlu7fh+TAq553nOSgw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14uepygtepskwehywergh9fe9j2a3ytqd80y9r2ekfmett6rq3peqjtgxns
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGY1ZoYlZvWG04Zk9ZdXh2
        T0VWUk1oY0R0eEtpQnJRcWIzUXozQUlGOVRNCitxY0h5b3l6QnN2ejNZQ3Z1aXJX
        aWhuNjZtYVNlTi9vV2pJOXJ3dkpZQjQKLS0tIGtJdFNOaDVtWXQ5aTd5L1diTzhw
        c2RmaXczVnY0azVqWEtZTHQ5YUZFYkEK57cPtu0CelzVM9LFR/i3qUbAPt6HRAUZ
        jAlPDHIQqQWeJE7x8E3CwCT3Z7LyA3fgSlt8eZ/n1OE6hNc1uWRz4Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1y5lqafxarcnlrduh8k3tycnaq63v2alagmtkf0k9gd59pg263axqtt928v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOalFvczJlL2xpUlVEblRD
        TGlid0dzRWhxYTBUZENVQzNESGtyTmkvcVFJCmxtWDQyb2VJNUNPaEVJVzVja0RK
        aEVOZ2ZsMmZTckduVGRzcHFWSUFJdjAKLS0tIFRHZ3M0dUlob0p6R0JPQlpSWG0x
        cm1sN3U1VnZNNTU1NFQ2UlRmSUJiVUkKcDxNEToerq/aAa+m8Bmyg9R+UsuMXwx/
        1guqoWy3m4ucGQBi7eCswg5m+rGee+FgzlQsan9EQwL8Zhh8sTwlaQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-10-21T18:45:20Z"
  mac: ENC[AES256_GCM,data:wZHWsdlyNGG4nFv1XsG3QscadSobCcReglVE7aQxf9o4WZsL/prWhyB0qhBpSGZXfMKISwkaTuDLVgSC7MQGYC6ybs6vFAQpFgkERb+fBgk/xJHZ3ahxJoftwiB2LLRmUshHqso5YeasSnFYt5vR/xhuTsUV6X+atatL+BHCpe8=,iv:NHQ37IAAvMWn5V/89XEcfPpvl9cUPbodMaKJ3ufx8Ss=,tag:TO1mZ1ajmd5Frq/OhC9ZRA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
