# Create HTTP ingress route for diamond
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: diamond-http
spec:
  entryPoints:
    # Use entrypoint for HTTPS traffic
    - https
  routes:
    # Match traffic with the Host header
    - match: HostRegexp(`diamond\..*`)
      kind: Rule
      services:
        # Route traffic to the diamond service
        - name: diamond
          # This is the name of the port in the service
          port: http
          # Use HTTPS when communicating with the service
          scheme: https
