# Create SQL ingress route for diamond
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: diamond-sql
spec:
  entryPoints:
    # Use entrypoint for diamond SQL traffic
    - diamond-sql
  routes:
    # Match all traffic
    - match: HostSNI(`*`)
      services:
        # Route traffic to the diamond service
        - name: diamond
          # This is the name of the port in the service
          port: sql
