# Create traefik Helm release
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
spec:
  chart:
    spec:
      # Use this chart from the repository
      chart: traefik
      # Pin version to major
      version: "26.x"
      # Use this Helm repository
      sourceRef:
        kind: HelmRepository
        name: traefik
  # This key always needs to be here for patching to work
  postRenderers: []
  values:
    # Use Traefik v3
    image:
      tag: "v3.0"
    # Additional arguments for the traefik binary
    additionalArguments:
      # Allow backends to use self-signed certificates
      - --serversTransport.insecureSkipVerify=true
      - --tcpServersTransport.tls.insecureSkipVerify=true
    # Disable the dashboard
    ingressRoute:
      dashboard:
        enabled: false
    # Disable Prometheus metrics
    metrics:
      prometheus: false
    # Entrypoints
    ports:
      # Disable default ports
      web: false
      websecure: false
      metrics: false
      # Port for HTTP traffic
      http:
        # Expose it outside the cluster
        expose: true
        # Expose it on this port
        exposedPort: 80
        # HTTP traffic uses TCP
        protocol: TCP
        # Port to use inside the cluster
        port: 8080
        # Redirect to HTTPS
        redirectTo:
          port: https
      # Port for HTTPS traffic
      https:
        # Expose it outside the cluster
        expose: true
        # Expose it on this port
        exposedPort: 443
        # Secure web traffic uses TCP
        protocol: TCP
        # Port to use inside the cluster
        port: 8443
        # Enable TLS
        tls:
          enabled: true
      # Port for TLS over TCP traffic
      tls-tcp:
        # Expose it outside the cluster
        expose: true
        # Expose it on this port
        exposedPort: 10000
        # TCP traffic uses TCP
        protocol: TCP
        # Port to use inside the cluster
        port: 10000
        # Enable TLS
        tls:
          enabled: true
      # Port for emifuse SRT traffic
      emifuse-srt:
        # Expose it outside the cluster
        expose: true
        # Expose it on this port
        exposedPort: 9999
        # emifuse SRT traffic uses UDP
        protocol: UDP
        # Port to use inside the cluster
        port: 9999
      # Port for datashows SQL traffic
      datashows-sql:
        # Expose it outside the cluster
        expose: true
        # Expose it on this port
        exposedPort: 9998
        # datashows SQL traffic uses TCP
        protocol: TCP
        # Port to use inside the cluster
        port: 9998
        # Enable TLS passthrough
        tls:
          passthrough: true
      # Port for emirecords SRT traffic
      emirecords-srt:
        # Expose it outside the cluster
        expose: true
        # Expose it on this port
        exposedPort: 9997
        # emirecords SRT traffic uses UDP
        protocol: UDP
        # Port to use inside the cluster
        port: 9997
      # Port for emistream SRT traffic
      emistream-srt:
        # Expose it outside the cluster
        expose: true
        # Expose it on this port
        exposedPort: 9996
        # emistream SRT traffic uses UDP
        protocol: UDP
        # Port to use inside the cluster
        port: 9996
      # Port for emipass RTP traffic
      emipass-rtp:
        # Expose it outside the cluster
        expose: true
        # Expose it on this port
        exposedPort: 9995
        # emipass RTP traffic uses UDP
        protocol: UDP
        # Port to use inside the cluster
        port: 9995
      # Port for datatunes SQL traffic
      datatunes-sql:
        # Expose it outside the cluster
        expose: true
        # Expose it on this port
        exposedPort: 9994
        # datatunes SQL traffic uses TCP
        protocol: TCP
        # Port to use inside the cluster
        port: 9994
        # Enable TLS passthrough
        tls:
          passthrough: true
    service:
      annotations:
        # Use custom machine name in Tailscale
        tailscale.com/hostname: traefik
      # Use Tailscale LoadBalancer
      loadBalancerClass: tailscale
