# Create traefik Helm release
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
spec:
  chart:
    spec:
      # Use this chart from the repository
      chart: traefik
      # Use this Helm repository
      sourceRef:
        kind: HelmRepository
        name: traefik
  # This key always needs to be here for patching to work
  postRenderers: []
  values:
    # Additional arguments for the traefik binary
    additionalArguments:
      # Allow backends to use self-signed certificates
      - --serversTransport.insecureSkipVerify=true
    # Disable the dashboard
    ingressRoute:
      dashboard:
        enabled: false
    # Disable Prometheus metrics
    metrics:
      prometheus: false
    # Entrypoints
    ports:
      # Disable default ports
      web: false
      websecure: false
      metrics: false
      # Port for HTTP traffic
      http:
        # Expose it outside the cluster
        expose: true
        # Expose it on this port
        exposedPort: 443
        # Secure web traffic uses TCP
        protocol: TCP
        # Port to use inside the cluster
        port: 8443
        # Enable TLS
        tls:
          enabled: true
      # Port for TCP traffic
      tcp:
        # Expose it outside the cluster
        expose: true
        # Expose it on this port
        exposedPort: 10000
        # TCP traffic uses TCP
        protocol: TCP
        # Port to use inside the cluster
        port: 10000
        # Enable TLS
        tls:
          enabled: true
      # Port for fusion SRT traffic
      fusion-srt:
        # Expose it outside the cluster
        expose: true
        # Expose it on this port
        exposedPort: 9999
        # fusion SRT traffic uses UDP
        protocol: UDP
        # Port to use inside the cluster
        port: 9999
    service:
      annotations:
        # Use custom machine name in Tailscale
        tailscale.com/hostname: traefik
      # Use Tailscale LoadBalancer
      loadBalancerClass: tailscale
