# Configure names transformer
nameReference:
  - kind: Secret
    version: v1
    fieldSpecs:
      # Replace secret names in HelmReleases
      - path: spec/valuesFrom/name
        kind: HelmRelease
