# Create HTTP ingress route for emishows
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: emishows-http
spec:
  entryPoints:
    # Use entrypoint for HTTPS traffic
    - https
  routes:
    # Match traffic with the Host header
    - match: HostRegexp(`emishows\..*`)
      kind: Rule
      services:
        # Route traffic to the emishows service
        - name: emishows
          # This is the name of the port in the service
          port: http
