# Create longhorn Helm release
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  chart:
    spec:
      # Use this chart from the repository
      chart: longhorn
      # Pin version to major
      version: "1.x"
      # Use this Helm repository
      sourceRef:
        kind: HelmRepository
        name: longhorn
  # This key always needs to be here for patching to work
  postRenderers: []
  values:
    csi:
      # Use only 1 replica of attacher
      attacherReplicaCount: 1
      # Use only 1 replica of provisioner
      provisionerReplicaCount: 1
      # Use only 1 replica of resizer
      resizerReplicaCount: 1
      # Use only 1 replica of snapshotter
      snapshotterReplicaCount: 1
    defaultSettings:
      # Allow taking snapshots or backups of detached volumes
      allowRecurringJobWhileVolumeDetached: true
      # Store data only on labeled nodes
      createDefaultDiskLabeledNodes: true
      # Use data locality when possible by default
      defaultDataLocality: best-effort
      # Use only 1 replica by default
      defaultReplicaCount: 1
    longhornUI:
      # Use only 1 replica of Longhorn UI
      replicas: 1
    # Use longhorn namespace for all resources
    namespaceOverride: longhorn
    persistence:
      # Use only 1 replica by default
      defaultClassReplicaCount: 1
      # Use data locality when possible by default
      defaultDataLocality: best-effort
      # Don't delete volumes when volume claims are deleted
      reclaimPolicy: Retain
    preUpgradeChecker:
      # Disable the pre-upgrade checker
      jobEnabled: false
