# Create cnpg Helm release
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
spec:
  chart:
    spec:
      # Use this chart from the repository
      chart: cloudnative-pg
      # Pin version to major
      version: "0.x"
      # Use this Helm repository
      sourceRef:
        kind: HelmRepository
        name: cnpg
  # This key always needs to be here for patching to work
  postRenderers: []
