# Create longhorn Helm release
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
spec:
  chart:
    spec:
      # Use this chart from the repository
      chart: longhorn
      # Use this Helm repository
      sourceRef:
        kind: HelmRepository
        name: longhorn
  # This needs to be here for patching to work
  postRenderers: []
  values:
    defaultSettings:
      # Store data only on labeled nodes
      createDefaultDiskLabeledNodes: true
      # Use data locality when possible by default
      defaultDataLocality: best-effort
      # Use only 1 replica by default
      defaultReplicaCount: 1
    # Use longhorn namespace for all resources
    namespaceOverride: longhorn
    persistence:
      # Use only 1 replica by default
      defaultClassReplicaCount: 1
      # Use data locality when possible by default
      defaultDataLocality: best-effort
    preUpgradeChecker:
      # Disable the pre-upgrade checker
      jobEnabled: false
