# Create SRT ingress route for emistream
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: emistream-srt
spec:
  entryPoints:
    # Use entrypoint for emistream SRT traffic
    - emistream-srt
  routes:
    - services:
        # Route traffic to the emistream service
        - name: emistream
          # This is the name of the port in the service
          port: srt
