# Create medialounge Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: medialounge
spec:
  # Path inside repository to a directory containing Kustomization files
  path: src/clusters/main/databases/medialounge/kustomize
  dependsOn:
    # Deploy Longhorn first
    - name: longhorn
    # Deploy Traefik first
    - name: traefik
  # Apply patches for common configurations
  # This key always needs to be here for patching to work
  patches:
    # Set target namespace
    - target:
        group: kustomize.toolkit.fluxcd.io
        kind: Kustomization
        name: .*
      patch: |
        kind: .
        metadata:
          name: .
        spec:
          targetNamespace: medialounge
