# Create datatimes-traefik Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: datatimes-traefik
spec:
  # Path inside repository to a directory containing Kustomization files
  path: src/clusters/main/databases/datatimes/kustomize/datatimes-traefik/kustomize
  dependsOn:
    # Deploy Helm release first
    - name: datatimes-helm
  # This key always needs to be here for patching to work
  patches: []
