# Create emicast Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Include the following resources
resources:
  - emicast-helm/emicast-helm.yaml
  - emicast-namespace/emicast-namespace.yaml
  - emicast-traefik/emicast-traefik.yaml
