jasmine:
  secrets:
    auth:
      - ENC[AES256_GCM,data:4W/S6zGy,iv:CyF90klWr7PEIW8P114dT5q5702Dsv7OWq82IkM4UbA=,tag:21Y4c+K0TE20Wp2vZIuc+Q==,type:str]
  scorpion:
    public:
      client: ENC[AES256_GCM,data:GHcE6WncSQ==,iv:rUSwWJFVujeV3/wjRyXp+s+f6GuYkGWYOWocRWLm2iY=,tag:/esUolmCx22CegVAC73XmQ==,type:str]
      secret: ENC[AES256_GCM,data:xsHQtYtz,iv:dA4QQVOaVFb87RR11sVY3yJVCE4k5oA9M01gB3xvlVs=,tag:XEMy76C30N9obuul5h5eDA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14uepygtepskwehywergh9fe9j2a3ytqd80y9r2ekfmett6rq3peqjtgxns
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGY1ZoYlZvWG04Zk9ZdXh2
        T0VWUk1oY0R0eEtpQnJRcWIzUXozQUlGOVRNCitxY0h5b3l6QnN2ejNZQ3Z1aXJX
        aWhuNjZtYVNlTi9vV2pJOXJ3dkpZQjQKLS0tIGtJdFNOaDVtWXQ5aTd5L1diTzhw
        c2RmaXczVnY0azVqWEtZTHQ5YUZFYkEK57cPtu0CelzVM9LFR/i3qUbAPt6HRAUZ
        jAlPDHIQqQWeJE7x8E3CwCT3Z7LyA3fgSlt8eZ/n1OE6hNc1uWRz4Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1y5lqafxarcnlrduh8k3tycnaq63v2alagmtkf0k9gd59pg263axqtt928v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOalFvczJlL2xpUlVEblRD
        TGlid0dzRWhxYTBUZENVQzNESGtyTmkvcVFJCmxtWDQyb2VJNUNPaEVJVzVja0RK
        aEVOZ2ZsMmZTckduVGRzcHFWSUFJdjAKLS0tIFRHZ3M0dUlob0p6R0JPQlpSWG0x
        cm1sN3U1VnZNNTU1NFQ2UlRmSUJiVUkKcDxNEToerq/aAa+m8Bmyg9R+UsuMXwx/
        1guqoWy3m4ucGQBi7eCswg5m+rGee+FgzlQsan9EQwL8Zhh8sTwlaQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-04T23:55:02Z"
  mac: ENC[AES256_GCM,data:FKK1M0BrYREtPlM64wQVzKYBCoONzPzvs0idnZUOdleT9KOavfcjbfajaAIGb+l++7DbZk+yapvG+pxbRkJVEQFvHc/mJGL2DvWAjptxsk7QvpFTYBhenlEBnu5MTp2j/7NjB6UNukgYAvVtV1PlkH6dad3RCN99KU5D1pGdenI=,iv:xgbDC/drgEiMNy/r/vj2/qNZ937KrnDnQZJ5JTgXGk4=,tag:Wo/8fHwp3kY9sedXZPJNjg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
