# Create SRT ingress route for fusion
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: fusion-srt
spec:
  entryPoints:
    # Use entrypoint for fusion SRT traffic
    - fusion-srt
  routes:
    - services:
        # Route traffic to the fusion service
        - name: fusion
          # This is the name of the port in the service
          port: srt
