# Create HTTP ingress route for emishows-db
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: emishows-db-http
spec:
  entryPoints:
    # Use entrypoint for HTTPS traffic
    - https
  routes:
    # Match traffic with the Host header
    - match: HostRegexp(`emishows-db\..*`)
      kind: Rule
      services:
        # Route traffic to the emishows-db service
        - name: emishows-db
          # This is the name of the port in the service
          port: http
          # Use HTTPS when communicating with the service
          scheme: https
