# Create SQL ingress route for emishows-db
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: emishows-db-sql
spec:
  entryPoints:
    # Use entrypoint for TCP traffic
    - tcp
  routes:
    # Match traffic with SNI
    - match: HostSNIRegexp(`emishows-db\..*`)
      services:
        # Route traffic to the emishows-db service
        - name: emishows-db
          # This is the name of the port in the service
          port: sql
