# Create aster-traefik Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: aster-traefik
spec:
  # Path inside repository to a directory containing Kustomization files
  path: src/clusters/main/apps/aster/kustomize/aster-traefik/kustomize
  dependsOn:
    # Deploy Helm release first
    - name: aster-helm
  # This key always needs to be here for patching to work
  patches: []
