# Create HTTP ingress route for magnolia
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: magnolia-http
spec:
  entryPoints:
    # Use entrypoint for HTTPS traffic
    - https
  routes:
    # Match traffic with the Host header
    - match: HostRegexp(`magnolia\..*`)
      kind: Rule
      services:
        # Route traffic to the magnolia service
        - name: magnolia
          # This is the name of the port in the service
          port: http
