# Create streamcast-traefik Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: streamcast-traefik
spec:
  # Path inside repository to a directory containing Kustomization files
  path: src/clusters/main/apps/streamcast/kustomize/streamcast-traefik/kustomize
  dependsOn:
    # Deploy Helm release first
    - name: streamcast-helm
  # This key always needs to be here for patching to work
  patches: []
