# Create HTTP ingress route for emirecords
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: emirecords-http
spec:
  entryPoints:
    # Use entrypoint for HTTPS traffic
    - https
  routes:
    # Match traffic with the Host header
    - match: HostRegexp(`emirecords\..*`)
      kind: Rule
      services:
        # Route traffic to the emirecords service
        - name: emirecords
          # This is the name of the port in the service
          port: http
