# Create tailscale-helm Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale-helm
spec:
  # Path inside repository to a directory containing Kustomization files
  path: src/clusters/main/infrastructure/tailscale/kustomize/tailscale-helm/kustomize
  dependsOn:
    # Deploy namespace first
    - name: tailscale-namespace
  # This key always needs to be here for patching to work
  patches: []
