# Create HTTP ingress route for jasmine
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jasmine-http
spec:
  entryPoints:
    # Use entrypoint for HTTPS traffic
    - https
  routes:
    # Match traffic with the Host header
    - match: HostRegexp(`jasmine\..*`)
      kind: Rule
      services:
        # Route traffic to the jasmine service
        - name: jasmine
          # This is the name of the port in the service
          port: http
