# Create beaver-helm Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: beaver-helm
spec:
  # Path inside repository to a directory containing Kustomization files
  path: src/clusters/main/services/beaver/kustomize/beaver-helm/kustomize
  dependsOn:
    # Deploy namespace first
    - name: beaver-namespace
  # This key always needs to be here for patching to work
  patches: []
