# Create HTTP ingress route for obsidian
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: obsidian-http
spec:
  entryPoints:
    # Use entrypoint for HTTPS traffic
    - https
  routes:
    # Match traffic with the Host header
    - match: HostRegexp(`obsidian\..*`)
      kind: Rule
      services:
        # Route traffic to the obsidian service
        - name: obsidian
          # This is the name of the port in the service
          port: http
          # Use HTTPS when communicating with the service
          scheme: https
