# Create SQL ingress route for obsidian
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: obsidian-sql
spec:
  entryPoints:
    # Use entrypoint for obsidian SQL traffic
    - obsidian-sql
  routes:
    # Match all traffic
    - match: HostSNI(`*`)
      services:
        # Route traffic to the obsidian service
        - name: obsidian
          # This is the name of the port in the service
          port: sql
