# Create HTTP ingress route for emitunes
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: emitunes-http
spec:
  entryPoints:
    # Use entrypoint for HTTPS traffic
    - https
  routes:
    # Match traffic with the Host header
    - match: HostRegexp(`emitunes\..*`)
      kind: Rule
      services:
        # Route traffic to the emitunes service
        - name: emitunes
          # This is the name of the port in the service
          port: http
