# Create medialounge-traefik Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: medialounge-traefik
spec:
  # Path inside repository to a directory containing Kustomization files
  path: src/clusters/main/databases/medialounge/kustomize/medialounge-traefik/kustomize
  dependsOn:
    # Deploy Helm release first
    - name: medialounge-helm
  # This key always needs to be here for patching to work
  patches: []
