# Create emishows-db Helm release
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emishows-db
spec:
  chart:
    spec:
      # Use this chart from the repository
      chart: emishows-db
      # Pin version to major
      version: "0.x"
      # Use this Helm repository
      sourceRef:
        kind: HelmRepository
        name: radio-aktywne
  # This key always needs to be here for patching to work
  postRenderers: []
  values:
    volume:
      # Use ReadWriteOnce access mode
      access: ReadWriteOnce
      # Use Longhorn storage class
      class: longhorn
      # Use 4 Gigabyte volume size
      size: 4Gi
  valuesFrom:
    - kind: Secret
      name: emishows-db-helm-secrets-values
      valuesKey: values.yaml
