# Configure replacements for OIDC middleware secret names
source:
  kind: Secret
  name: traefik-config-secrets-oidc
  fieldPath: metadata.name
targets:
  # Replace secret names in OIDC middleware
  - select:
      group: traefik.io
      kind: Middleware
      name: oidc
    fieldPaths:
      - spec.plugin.traefikoidc.clientSecret
      - spec.plugin.traefikoidc.sessionEncryptionKey
    options:
      delimiter: ":"
      index: 3
