# Create HTTPS ingress route for streamcast
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: streamcast-https
spec:
  entryPoints:
    # Use entrypoint for secure web traffic
    - websecure
  routes:
    # Match traffic with the Host header
    - match: HostRegexp(`streamcast.{domain:.*}`)
      kind: Rule
      services:
        # Route traffic to the streamcast service
        - name: streamcast
          # This is the name of the port in the service
          port: http
