# Create HTTP ingress route for streamcast
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: streamcast-http
spec:
  entryPoints:
    # Use entrypoint for HTTP traffic
    - http
  routes:
    # Match traffic with the Host header
    - match: HostRegexp(`streamcast.{domain:.*}`)
      kind: Rule
      services:
        # Route traffic to the streamcast service
        - name: streamcast
          # This is the name of the port in the service
          port: http
