apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  chart:
    spec:
      chart: podinfo
      interval: 1m
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: default
  interval: 1m
