# Create certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate
spec:
  # Include the following DNS names in the Subject Alt Name field
  dnsNames:
    - "k8s.spietras.dev"
    - "*.k8s.spietras.dev"
    - "*.flux.k8s.spietras.dev"
    - "*.headlamp.k8s.spietras.dev"
    - "*.longhorn.k8s.spietras.dev"
    - "*.amber.k8s.spietras.dev"
    - "*.diamond.k8s.spietras.dev"
    - "*.emerald.k8s.spietras.dev"
    - "*.graphite.k8s.spietras.dev"
    - "*.howlite.k8s.spietras.dev"
    - "*.minium.k8s.spietras.dev"
    - "*.obsidian.k8s.spietras.dev"
    - "*.sapphire.k8s.spietras.dev"
    - "*.beaver.k8s.spietras.dev"
    - "*.dingo.k8s.spietras.dev"
    - "*.falcon.k8s.spietras.dev"
    - "*.gecko.k8s.spietras.dev"
    - "*.loris.k8s.spietras.dev"
    - "*.mantis.k8s.spietras.dev"
    - "*.numbat.k8s.spietras.dev"
    - "*.octopus.k8s.spietras.dev"
    - "*.pelican.k8s.spietras.dev"
    - "*.quokka.k8s.spietras.dev"
    - "*.scorpion.k8s.spietras.dev"
    - "*.aster.k8s.spietras.dev"
    - "*.crocus.k8s.spietras.dev"
    - "*.daisy.k8s.spietras.dev"
    - "*.jasmine.k8s.spietras.dev"
    - "*.lotus.k8s.spietras.dev"
    - "*.magnolia.k8s.spietras.dev"
    - "*.orchid.k8s.spietras.dev"
    - "*.podinfo.k8s.spietras.dev"
    - "*.poppy.k8s.spietras.dev"
    - "*.tulip.k8s.spietras.dev"
  # Use Let's Encrypt to issue the certificate
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  # Store the certificate in the following secret
  # This secret will be created automatically by cert-manager
  secretName: certificate
