# Create default TLS store
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
spec:
  # Use the default certificate for all routes
  defaultCertificate:
    secretName: certificate
