# Create HTTP ingress route for tulip
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tulip-http
spec:
  entryPoints:
    # Use entrypoint for HTTPS traffic
    - https
  routes:
    # Match traffic with the Host header
    - match: HostRegexp(`tulip\..*`)
      kind: Rule
      services:
        # Route traffic to the tulip service
        - name: tulip
          # This is the name of the port in the service
          port: http
