# Create webscheduler Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Include the following resources
resources:
  - webscheduler-helm/webscheduler-helm.yaml
  - webscheduler-namespace/webscheduler-namespace.yaml
  - webscheduler-traefik/webscheduler-traefik.yaml
